### ISSUE TITLE
Large jars are deployed in maven repository

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-packages#10]
We use spring-boot-maven plugin to create a jar file for a freme package that includes all depdencies using a classifier. So two jar files are created out of a freme package, the normal jar (typically a few kb of size) and the full jar (size a few hundred mb).

The problem is that both jars get deployed to the maven repository. We need only the normal jar in the maven repository.

**Comment by ArneBinder** [comment]
Possible solution: using maven [build profiles](http://maven.apache.org/guides/introduction/introduction-to-profiles.html).

**Comment by ArneBinder** [comment]
Created profile `full-assembly` (see branch `maven-build-profile`) in package-parent, which is enabled by default. To disable the deployment of the full jar execute `mvn deploy -P !full-assembly`.

**Comment by jnehring** [comment]
I configured nexus to delete old jars so this is no longer problematic
