### ISSUE TITLE
Add database init-scripts to broker-local

### ISSUE THREAD

**Issue by ArneBinder** [freme-project/freme-packages#14]
@jnehring should we do so? The article [Getting started with FREME development](http://api-dev.freme-project.eu/doc/knowledge-base/freme-for-developers/developers-getting-started.html) states that the package broker-local 

> contains a complete configuration, meaning that the configuration works out of the box.

But without any templates or postprocessing filters this doesnt seem so usefull.

**Comment by jnehring** [comment]
Good idea! Please add the init scripts and the configuration to execute them.

**Comment by ArneBinder** [comment]
I added the scripts and enabled the autoload.
@bgrusdt please can you verify if this works with the `start_server.sh` script? It deosnt work on my windows machine. Thanks!

**Comment by jnehring** [comment]
Why does the script not work on your windows machine? The documentation [Getting started with FREME development](http://api-dev.freme-project.eu/doc/knowledge-base/freme-for-developers/developers-getting-started.html) and [Initialising FREME](http://api-dev.freme-project.eu/doc/knowledge-base/freme-for-sysadmins/initialising-freme.html) do not mention a problem with windows.

**Comment by ArneBinder** [comment]
@jnehring I get the following:
```
c:\Users\arbi01\Developing\intellij-workspace\Freme\freme-packages\broker-local\target\freme-package>sh bin\start_server.sh
bin\start_server.sh: line 19: readlink: command not found
bin\start_server.sh: line 29: config/pid.txt: No such file or directory
Started FREME
```
```
c:\Users\arbi01\Developing\intellij-workspace\Freme\freme-packages\broker-local\target\freme-package>sh bin\start_local.sh
bin\start_local.sh: line 19: readlink: command not found
Fehler: Hauptklasse org.springframework.boot.loader.JarLauncher konnte nicht gefunden oder geladen werden
```

Freme doesnt start in any case.

**Comment by bgrusdt** [comment]
FREME starts with the start_server script on my machine. I tried out: GET http://{{baseUrl}}/e-link/templates which returns the templates, so it seems to work fine.

**Comment by jnehring** [comment]
thanks. this issue is finished.
