### ISSUE TITLE
[broker-local] init-xsltconverter script

### ISSUE THREAD

**Issue by ArneBinder** [freme-project/freme-packages#16]
Currently there are two scripts:
* [init-xsltconverter.h2.sql](https://github.com/freme-project/freme-packages/blob/master/broker-local/src/main/resources/init-xsltconverter.h2.sql)
* [init-xsltconverter.mysql.sql](https://github.com/freme-project/freme-packages/blob/master/broker-local/src/main/resources/init-xsltconverter.mysql.sql)

They both work for its case. Should we put any effords in creating one script for both, h2 and mysql?
[Initialising FREME](http://api-dev.freme-project.eu/doc/knowledge-base/freme-for-sysadmins/initialising-freme.html) already documents the two cases.

**Comment by jnehring** [comment]
It is ok like this. Thank you.

**Comment by ArneBinder** [comment]
The scripts have to be updated with the fixed stylesheets, see https://github.com/freme-project/freme-packages/issues/17.

**Comment by ArneBinder** [comment]
Fixed.
