### ISSUE TITLE
incorrect XSLT stylesheets

### ISSUE THREAD

**Issue by ArneBinder** [freme-project/freme-packages#17]
During the re-import of the database dump some escaping errors occured. @fsasaki could you please update the content of the following xslt converters:
* tei2temp-html
* html-to-xliff20
* xslt-30-test

Thanks!

**Comment by fsasaki** [comment]
Done, please check.

**Comment by ArneBinder** [comment]
Thanks!
But `html-to-xliff20` doesnt work for me. Try:

```
curl -X POST -H "Content-Type: text/html" -d '<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <title>dummy title</title>
    </head>
    <body>
        <div id="xyz1xyz">
            <p id="n1">We very much welcome you in the city of Prague, a home of XML!</p>
        </div>
    </body>
</html>' "http://api-dev.freme-project.eu/current/toolbox/xslt-converter/documents/html-to-xliff20"
```

Result:

```
{
  "exception": "eu.freme.common.exception.FREMEHttpException",
  "path": "/toolbox/xslt-converter/documents/html-to-xliff20",
  "message": "The XML parser reported one validation error",
  "error": "Internal Server Error",
  "status": 500,
  "timestamp": 1469553936662
}
```

Did this work before?

How to check `xslt-30-test`?

**Comment by fsasaki** [comment]
This works with content type text/xml. It should also work with content type text/html . This is an issue not of the xslt-30-test stylesheet but I think of the setting of the validator.nu parser. The message "The XML parser reported one validation error" probably comes from validator.nu. Can you set the call of validator.nu so that it does not do validation?

**Comment by ArneBinder** [comment]
OK, this could work. I seems to be possible to pass a validation level to the parser. I will have a look at this when I'm back in office.
