### ISSUE TITLE
Disable monitoring

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-packages#18]
Please disable the monitoring of
* e-translation
* e-terminology
* dbpedia spotlight

These three services produce so many messages that I easily miss important monitoring messages.

**Comment by jnehring** [comment]
or is it possible to just disable the notification, so we can still gather the statistics?

**Comment by ArneBinder** [comment]
I changed the severity level to `not classified`, so just I get notification mails for these triggers.

**Comment by ArneBinder** [comment]
@jnehring can we close this?

**Comment by jnehring** [comment]
Thank you! I leave it open for a while to test if it really works. I did not get any notification emails since yesterday 14:42 which is unusual.

**Comment by jnehring** [comment]
Works fine thanks!
