### ISSUE TITLE
Update logging configuration

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-packages#19]
When FREME is restarted then the log files should append new information to the existing log files instead of deleting the old log files and starting a new log file. This change needs to be configured in `src/main/resources/log4j.properties` of the packages broker-dev and freme-ner-dev. This configuration should be added to

* broker-dev
* broker-local
* freme-full
* freme-ner-dev

**Comment by bgrusdt** [comment]
This is done. In the four packages, logging is now appended to the exsiting log file.
