### ISSUE TITLE
Add XSLT converter and urlsupport-filter

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-packages#20]
Please add the two basic services to the packages

* broker-local
* freme-full
* freme-ner-dev

It might not be necessary to add the urlsupport filter to freme-ner-dev because it is possible that the broker already downloads the url. Please test if this already works for freme-ner. When it already works, then do not add the urlsupport filter to freme-ner-dev.

**Comment by jnehring** [comment]
It is only necessary to add this to freme-ner-dev

**Comment by bgrusdt** [comment]
I added the two basic services.
