### ISSUE TITLE
Uncompilable source code - package org.slf4j does not exist

### ISSUE THREAD

**Issue by pheyvaer** [freme-project/freme-packages#21]
I've made some changes to `epublib-core` and `publishing`, and I want to test them via `broker-local`. However, I get the following error when running the broker `java.lang.RuntimeException: Uncompilable source code - package org.slf4j does not exist`. What might be the cause of this? I see that in the `pom.xml` of `publishing` `org.slf4j` is excluded. However, including it again still gives the same error.

**Comment by jnehring** [comment]
* I cloned the repository and could run "mvn package" on the broker-local package. No problems.
* Then I deleted my local repository `rm ~/.m2/repository/eu/freme/` and did mvn package agin. No problems
* Then I tried `mvn clean install` and it still works.

Please give me more information on how to reproduce the error.

**Comment by pheyvaer** [comment]
I made changes to both `epublib-core` and `publishing`. In `broker-local` I updated the `pom.xml` to use the new version of `publishing`. The same for `publishing` and `epublib-core`. Building all the packages works, but it fails when running `broker-local`.

**Comment by jnehring** [comment]
How can I reproduce this? Did you commit the changes in the repository? The last commit in [epublib repo](https://github.com/freme-project/epublib/tree/master) is 8 month ago. Can you please push your changes to a new branch? Otherwise I think I cannot help you.

**Comment by pheyvaer** [comment]
I've pushed my changes to the branch `fix23` in the repos `epublib`, `freme-packages` and `e-services`.

**Comment by jnehring** [comment]
I still do not get any errors in your code. I merged everything in the master and the code compiles fine on Jenkins. It is already deployed on freme-dev.

One think is odd: [e-publishing pom.xml](https://github.com/freme-project/e-services/blob/master/publishing/pom.xml#L144) pulls in epublib-core:0.3-SNAPSHOT. But the latest version of epublib-core is 0.4-SNAPSHOT. Is this correct?

**Comment by pheyvaer** [comment]
You merged? Did you run e-Publishing? Yes it should be the latest version.

**Comment by pheyvaer** [comment]
It seems to work now on my side. Thx!
