### ISSUE TITLE
Not latest version of publishing in broker

### ISSUE THREAD

**Issue by pheyvaer** [freme-project/freme-packages#22]
Is it possible that the broker doesn't use the latest version of `e-services.publishing`? I've done an update. However, the changes don't seem to appear on the dev version. Could it be that version `0.6` is used instead of `0.7-SNAPSHOT`? I had a similar problem locally and I had to force `broker-local` to use the latest version via the `pom.xml`.

**Comment by jnehring** [comment]
I updated the version of publishing in freme-parent from 0.6 to 0.7-SNAPSHOT. Please check if it works.

**Comment by pheyvaer** [comment]
Works, thx!
