### ISSUE TITLE
Deploy new live version

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-packages#25]
I have release freme 1.0. This is the final version of FREME. Please deploy the latest freme-full package at the ADAPT server.

**Comment by munnellg** [comment]
The new version of Freme fails to launch. Error log attached


[broker_error.txt](https://github.com/freme-project/freme-packages/files/721419/broker_error.txt)

**Comment by jnehring** [comment]
The system cannot allocate enough RAM. Please add (or update existing) file config/start-properties in your FREME package and change the content to

```
START_ARGS="-Xmx16G -Djava.security.egd=file:/dev/./urandom"
```

Now the system can allocate 16G of RAM.

This information is not in the documentation. I will add it: https://github.com/freme-project/freme-project.github.io/issues/331

**Comment by munnellg** [comment]
@jnehring The new version should now be deployed with those settings

**Comment by jnehring** [comment]
looks good! the issue is solved.
